version: "3.7"

services:
  engine:
    links:
      - db
    build:
      context: ./airflow
      args:
        airflow_cfg: ./airflow.cfg
    container_name: airflow-engine
    volumes:
      - ./airflow/dags:/airflow/dags
      - ./airflow/plugins:/airflow/plugins
    ports:
      - "8080:8080"
    tty: True

  db:
    build:
      context: ./mysql
    container_name: airflow-db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: pswd
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: pswd
    volumes:
      - mysql-initdata:/var/lib/mysql
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake

volumes:
  mysql-initdata:
