name: Docker Image CI

on: [ push ]

jobs:

  up:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start the Airflow image
      run: |
        docker-compose up -d db
        sleep 60
        docker-compose up -d engine

    - name: Check the Airflow image
      run: |
        docker-compose exec -T engine airflow version
        docker-compose exec -T engine airflow checkdb
        # docker exec airflow-engine airflow list_dags
