name: Docker Image CI

on: [ push ]

jobs:

  up:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start the Airflow image
      run: |
        docker-compose up -d engine
        sleep 60

    - name: Check the Airflow image
      run: |
      docker exec -it airflow-engine airflow version
      docker exec -it airflow-engine airflow checkdb
      # docker exec airflow-engine airflow list_dags
