name: Docker Image CI

on: [ push ]

jobs:

  up:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start the Airflow image
      run: |
        docker-compose up engine
        sleep 60

    - name: Check the Airflow image
      run: |
        docker-compose exec engine airflow version
        docker-compose exec engine airflow checkdb
        docker-compose exec engine airflow list_dags
