name: Docker Image CI

on: [ push ]

jobs:

  up:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start the Airflow image
      run: |
        docker-compose up -d engine

    - name: Check the Airflow image
      run: |
        docker-compose exec engine bash -c "airflow version"
        docker-compose exec engine bash -c "airflow checkdb"
        # docker exec airflow-engine airflow list_dags
